import Head from 'next/head';

export default function Home({ hello }: { hello: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-lg font-semibold text-blue-500'>{hello}</h1>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      hello: 'Hello World',
    },
  };
}
